[package]
name = "blockchain"
version = "0.1.0"
authors = ["tugce <yalntue.teyn@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
arrayref = "0.3.6"

